name: Auto approve
'on': pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3.0.0
        if: github.actor == 'dependabot[bot]'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
